#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : backports.entry_points_selectable
Version  : 1.0.3
Release  : 3
URL      : https://files.pythonhosted.org/packages/6b/3f/a0466ad0b536a1dbcf54ec79c4b0f92fdd8ede0407f9246486eadf9e13fb/backports.entry_points_selectable-1.0.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/6b/3f/a0466ad0b536a1dbcf54ec79c4b0f92fdd8ede0407f9246486eadf9e13fb/backports.entry_points_selectable-1.0.3.tar.gz
Summary  : Compatibility shim providing selectable entry points for older implementations
Group    : Development/Tools
License  : MIT
Requires: backports.entry_points_selectable-license = %{version}-%{release}
Requires: backports.entry_points_selectable-python = %{version}-%{release}
Requires: backports.entry_points_selectable-python3 = %{version}-%{release}
Requires: importlib_metadata
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : setuptools_scm-python
BuildRequires : tox
BuildRequires : virtualenv

%description
.. image:: https://img.shields.io/pypi/v/backports.entry_points_selectable.svg
:target: `PyPI link`_

%package license
Summary: license components for the backports.entry_points_selectable package.
Group: Default

%description license
license components for the backports.entry_points_selectable package.


%package python
Summary: python components for the backports.entry_points_selectable package.
Group: Default
Requires: backports.entry_points_selectable-python3 = %{version}-%{release}

%description python
python components for the backports.entry_points_selectable package.


%package python3
Summary: python3 components for the backports.entry_points_selectable package.
Group: Default
Requires: python3-core
Provides: pypi(backports.entry_points_selectable)

%description python3
python3 components for the backports.entry_points_selectable package.


%prep
%setup -q -n backports.entry_points_selectable-1.0.3
cd %{_builddir}/backports.entry_points_selectable-1.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1617718872
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/backports.entry_points_selectable
cp %{_builddir}/backports.entry_points_selectable-1.0.3/LICENSE %{buildroot}/usr/share/package-licenses/backports.entry_points_selectable/8e6689d37f82d5617b7f7f7232c94024d41066d1
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}/usr/lib/python3.9/site-packages/backports/__init__.py
rm -f %{buildroot}/usr/lib/python3.9/site-packages/backports/__pycache__/__init__.cpython-39.pyc

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/backports.entry_points_selectable/8e6689d37f82d5617b7f7f7232c94024d41066d1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
